# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: self
    type: git
    ref: main

#trigger:
#- main

pool:
  name: Self-hosted Tosca

stages:
- stage: build
  jobs:
    - job: run_build
      pool:
        name: Self-hosted Tosca
      steps:
      - task: PowerShell@2
        displayName: 'run_build > Steps > Task 1...'
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            #echo (Get-Date -Format "MM/dd/yyyy - HH:mm:ss-ffff") >> './hello world.txt'
            $param3 = "number 3"
            Write-Host $(param1)
            Write-Host $(param2)
            Write-Host $param3
      - task: PowerShell@2
        displayName: 'run_build > Steps > Task 2...'
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            #echo (Get-Date -Format "MM/dd/yyyy - HH:mm:ss-ffff") >> 'hello world.txt'
            Write-Host $(Pipeline.Workspace)
            Write-Host $(param2)
            Write-Host $param3   
#      - task: PublishPipelineArtifact@1
#        inputs:
#          targetPath: '$(Pipeline.Workspace)'
#          artifact: 'arti'
#          publishLocation: 'pipeline'

