# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: self
    type: git
    ref: main

#trigger:
#- main

pool:
  name: Self-hosted Tosca

stages:
- stage: build
  jobs:
    - job: build_test
      displayName: Job1::Build
      steps:
      - task: PowerShell@2
        displayName: Create results folder
        inputs:
          targetType: 'inline'
          script: if (!(Test-Path './results')) {New-Item './results' -ItemType Directory}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/results'
          artifact: 'arti'
          publishLocation: 'pipeline'

- stage: test
  jobs:
    - job: reun_tests
      displayName: Job2::Test
      steps:
      - task: PowerShell@2
        displayName: 'run_build > Steps > Task 1...'
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            #echo (Get-Date -Format "MM/dd/yyyy - HH:mm:ss-ffff") >> './hello world.txt'
            $param3 = "number 3"
            Write-Host $(param1)
            Write-Host $(param2)
            Write-Host $param3
      - task: PowerShell@2
        displayName: 'run_build > Steps > Task 2...'
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            #echo (Get-Date -Format "MM/dd/yyyy - HH:mm:ss-ffff") >> 'hello world.txt'
            Write-Host "Pipeline.Workspace: " $(Pipeline.Workspace)
            Write-Host "Build.ArtifactStagingDirectory:" $(Build.ArtifactStagingDirectory)
            Write-Host "system.JobId: "$(system.JobId)


